export interface TaxonomyArea {
  name: string;
  slug: string;
  aliases: string[];
  kind: "area" | "special";
  sortOrder: number;
}

export const WILDCARD_SLUG = "all-bengaluru";

export const CURATED_AREAS: TaxonomyArea[] = [
  { name: "All Bengaluru", slug: "all-bengaluru", aliases: ["All Bengaluru", "Everywhere", "Anywhere"], kind: "special", sortOrder: 0 },
  { name: "Indiranagar", slug: "indiranagar", aliases: ["Indiranagar", "Indranagar", "Indra Nagar"], kind: "area", sortOrder: 10 },
  { name: "Koramangala", slug: "koramangala", aliases: ["Koramangala", "Koramangla"], kind: "area", sortOrder: 11 },
  { name: "HSR Layout", slug: "hsr-layout", aliases: ["HSR Layout", "HSR"], kind: "area", sortOrder: 12 },
  { name: "Whitefield", slug: "whitefield", aliases: ["Whitefield"], kind: "area", sortOrder: 13 },
  { name: "BTM Layout", slug: "btm-layout", aliases: ["BTM Layout", "BTM"], kind: "area", sortOrder: 14 },
  { name: "J. P. Nagar", slug: "j-p-nagar", aliases: ["J. P. Nagar", "JP Nagar", "J P Nagar", "JPNagar"], kind: "area", sortOrder: 15 },
  { name: "Haralur", slug: "haralur", aliases: ["Haralur", "Harlur", "Haralur Road"], kind: "area", sortOrder: 16 },
  { name: "Bellandur", slug: "bellandur", aliases: ["Bellandur"], kind: "area", sortOrder: 17 },
  { name: "Sarjapur", slug: "sarjapur", aliases: ["Sarjapur", "Sarjapur Road"], kind: "area", sortOrder: 18 },
  { name: "Old Madras Road", slug: "old-madras-road", aliases: ["Old Madras Road", "Old Madras Rd", "OMR", "OMR East", "OMR-East"], kind: "area", sortOrder: 19 },
  { name: "CV Raman Nagar", slug: "cv-raman-nagar", aliases: ["CV Raman Nagar", "CV Raman", "C V Raman Nagar"], kind: "area", sortOrder: 20 },
  { name: "Brookefield", slug: "brookefield", aliases: ["Brookefield", "Brooke Field"], kind: "area", sortOrder: 21 },
  { name: "Marathahalli", slug: "marathahalli", aliases: ["Marathahalli", "Marathalli"], kind: "area", sortOrder: 22 },
  { name: "Electronic City", slug: "electronic-city", aliases: ["Electronic City", "E-City", "ECity"], kind: "area", sortOrder: 23 },
  { name: "Diamond District", slug: "diamond-district", aliases: ["Diamond District", "Diamond District Layout"], kind: "area", sortOrder: 24 },
  { name: "Jayanagar", slug: "jayanagar", aliases: ["Jayanagar"], kind: "area", sortOrder: 25 },
  { name: "Rajajinagar", slug: "rajajinagar", aliases: ["Rajajinagar", "Rajaji Nagar"], kind: "area", sortOrder: 26 },
  { name: "Banashankari", slug: "banashankari", aliases: ["Banashankari", "BSK"], kind: "area", sortOrder: 27 },
  { name: "Malleswaram", slug: "malleswaram", aliases: ["Malleswaram", "Malleshwaram"], kind: "area", sortOrder: 28 },
  { name: "Hebbal", slug: "hebbal", aliases: ["Hebbal"], kind: "area", sortOrder: 29 },
  { name: "Yelahanka", slug: "yelahanka", aliases: ["Yelahanka"], kind: "area", sortOrder: 30 },
  { name: "KR Puram", slug: "kr-puram", aliases: ["KR Puram", "Krishnarajapuram", "Kr Puram"], kind: "area", sortOrder: 31 },
  { name: "Ulsoor", slug: "ulsoor", aliases: ["Ulsoor", "Halasuru"], kind: "area", sortOrder: 32 },
  { name: "Domlur", slug: "domlur", aliases: ["Domlur", "Dommlur"], kind: "area", sortOrder: 33 },
  { name: "Hennur", slug: "hennur", aliases: ["Hennur", "Hennur Road"], kind: "area", sortOrder: 34 },
  { name: "Thanisandra", slug: "thanisandra", aliases: ["Thanisandra", "Thanisandra Main Road"], kind: "area", sortOrder: 35 },
  { name: "Kalyan Nagar", slug: "kalyan-nagar", aliases: ["Kalyan Nagar", "Kalyannagar", "HRBR Layout", "HRBR"], kind: "area", sortOrder: 36 },
  { name: "Frazer Town", slug: "frazer-town", aliases: ["Frazer Town", "Fraser Town"], kind: "area", sortOrder: 37 },
  { name: "Cooke Town", slug: "cooke-town", aliases: ["Cooke Town", "Cook Town"], kind: "area", sortOrder: 38 },
  { name: "Sadashivanagar", slug: "sadashivanagar", aliases: ["Sadashivanagar", "Sadashiva Nagar", "RMV", "RMV Extension"], kind: "area", sortOrder: 39 },
  { name: "Old Airport Road", slug: "old-airport-road", aliases: ["Old Airport Road", "Old Airport Rd", "OAR"], kind: "area", sortOrder: 40 },
  { name: "Varthur", slug: "varthur", aliases: ["Varthur", "Varthur Road"], kind: "area", sortOrder: 41 },
  { name: "Panathur", slug: "panathur", aliases: ["Panathur", "Panathur Main Road"], kind: "area", sortOrder: 42 },
  { name: "Gunjur", slug: "gunjur", aliases: ["Gunjur", "Gunjur Village"], kind: "area", sortOrder: 43 },
  { name: "Kadugodi", slug: "kadugodi", aliases: ["Kadugodi", "Kadugodi Tree Park"], kind: "area", sortOrder: 44 },
  { name: "Mahadevapura", slug: "mahadevapura", aliases: ["Mahadevapura", "Mahadevapura Post"], kind: "area", sortOrder: 45 },
  { name: "Kasavanahalli", slug: "kasavanahalli", aliases: ["Kasavanahalli", "Kasavanahalli Main Road"], kind: "area", sortOrder: 46 },
  { name: "Bannerghatta Road", slug: "bannerghatta-road", aliases: ["Bannerghatta Road", "Bannerghatta", "BG Road"], kind: "area", sortOrder: 47 },
  { name: "Kanakapura Road", slug: "kanakapura-road", aliases: ["Kanakapura Road", "Kanakapura Rd", "Kanakapura"], kind: "area", sortOrder: 48 },
  { name: "Uttarahalli", slug: "uttarahalli", aliases: ["Uttarahalli", "Uttarhalli"], kind: "area", sortOrder: 49 },
  { name: "Binnypete", slug: "binnypete", aliases: ["Binnypete", "Binny Pete", "BinnyPete"], kind: "area", sortOrder: 50 },
  { name: "Kaggadasapura", slug: "kaggadasapura", aliases: ["Kaggadasapura", "Kaggadasapura Main Road"], kind: "area", sortOrder: 51 },
  { name: "Hoodi", slug: "hoodi", aliases: ["Hoodi", "Hoodi Village"], kind: "area", sortOrder: 52 },
  { name: "Kammanahalli", slug: "kammanahalli", aliases: ["Kammanahalli", "Kammanahalli Main Road"], kind: "area", sortOrder: 53 },
  { name: "Banaswadi", slug: "banaswadi", aliases: ["Banaswadi", "Chikka Banaswadi", "Dodda Banaswadi"], kind: "area", sortOrder: 54 },
  { name: "Singasandra", slug: "singasandra", aliases: ["Singasandra", "Kudlu Gate", "Kudlu"], kind: "area", sortOrder: 55 },
  { name: "Kundalahalli", slug: "kundalahalli", aliases: ["Kundalahalli", "Kundalahalli Gate"], kind: "area", sortOrder: 56 },
  { name: "Murugeshpalya", slug: "murugeshpalya", aliases: ["Murugeshpalya", "Murgeshpalya", "Jeevan Bima Nagar", "Jeevanbhima Nagar"], kind: "area", sortOrder: 57 },
  { name: "Kodihalli", slug: "kodihalli", aliases: ["Kodihalli"], kind: "area", sortOrder: 58 },
  { name: "Kadubeesanahalli", slug: "kadubeesanahalli", aliases: ["Kadubeesanahalli"], kind: "area", sortOrder: 59 },
  { name: "Ramamurthy Nagar", slug: "ramamurthy-nagar", aliases: ["Ramamurthy Nagar", "Ramamurthynagar", "RM Nagar"], kind: "area", sortOrder: 60 },
  { name: "Horamavu", slug: "horamavu", aliases: ["Horamavu", "Horumavu"], kind: "area", sortOrder: 61 },
  { name: "Basavanagudi", slug: "basavanagudi", aliases: ["Basavanagudi", "Basavangudi"], kind: "area", sortOrder: 62 },
  { name: "Bommanahalli", slug: "bommanahalli", aliases: ["Bommanahalli"], kind: "area", sortOrder: 63 },
  { name: "Begur", slug: "begur", aliases: ["Begur", "Begur Road"], kind: "area", sortOrder: 64 },
  { name: "Basaveshwaranagar", slug: "basaveshwaranagar", aliases: ["Basaveshwaranagar", "Basaveshwara Nagar", "Basaveswaranagar"], kind: "area", sortOrder: 65 },
  { name: "Nagarbhavi", slug: "nagarbhavi", aliases: ["Nagarbhavi"], kind: "area", sortOrder: 66 },
  { name: "Chandra Layout", slug: "chandra-layout", aliases: ["Chandra Layout", "Chandralayout"], kind: "area", sortOrder: 67 },
  { name: "RR Nagar", slug: "rr-nagar", aliases: ["RR Nagar", "Rajarajeshwari Nagar", "Raja Rajeshwari Nagar"], kind: "area", sortOrder: 68 },
  { name: "Kengeri", slug: "kengeri", aliases: ["Kengeri", "Kengeri Satellite Town"], kind: "area", sortOrder: 69 },
  { name: "Vijayanagar", slug: "vijayanagar", aliases: ["Vijayanagar", "Vijay Nagar"], kind: "area", sortOrder: 70 },
  { name: "RT Nagar", slug: "rt-nagar", aliases: ["RT Nagar", "R T Nagar", "Jayamahal", "Jayamahal Road"], kind: "area", sortOrder: 71 },
  { name: "Sahakar Nagar", slug: "sahakar-nagar", aliases: ["Sahakar Nagar", "Sahakara Nagar", "Sahakarnagar"], kind: "area", sortOrder: 72 },
  { name: "Kodigehalli", slug: "kodigehalli", aliases: ["Kodigehalli"], kind: "area", sortOrder: 73 },
  { name: "Jakkur", slug: "jakkur", aliases: ["Jakkur", "Jakkur Aerodrome"], kind: "area", sortOrder: 74 },
  { name: "Chandapura", slug: "chandapura", aliases: ["Chandapura", "Chandapura Anekal Road"], kind: "area", sortOrder: 75 },
  { name: "Anekal", slug: "anekal", aliases: ["Anekal"], kind: "area", sortOrder: 76 },
  { name: "Central", slug: "central", aliases: ["Central", "Central Bangalore", "Bangalore Central"], kind: "area", sortOrder: 90 },
];
