insert into areas (name, slug, aliases, kind, source, sort_order) values
  ('All Bengaluru', 'all-bengaluru', '{"All Bengaluru","Everywhere","Anywhere"}', 'special', 'curated', 0),
  ('Indiranagar', 'indiranagar', '{"Indiranagar","Indranagar","Indra Nagar"}', 'area', 'curated', 10),
  ('Koramangala', 'koramangala', '{"Koramangala","Koramangla"}', 'area', 'curated', 11),
  ('HSR Layout', 'hsr-layout', '{"HSR Layout","HSR"}', 'area', 'curated', 12),
  ('Whitefield', 'whitefield', '{"Whitefield"}', 'area', 'curated', 13),
  ('BTM Layout', 'btm-layout', '{"BTM Layout","BTM"}', 'area', 'curated', 14),
  ('J. P. Nagar', 'j-p-nagar', '{"J. P. Nagar","JP Nagar","J P Nagar","JPNagar"}', 'area', 'curated', 15),
  ('Haralur', 'haralur', '{"Haralur","Harlur","Haralur Road"}', 'area', 'curated', 16),
  ('Bellandur', 'bellandur', '{"Bellandur"}', 'area', 'curated', 17),
  ('Sarjapur', 'sarjapur', '{"Sarjapur","Sarjapur Road"}', 'area', 'curated', 18),
  ('Old Madras Road', 'old-madras-road', '{"Old Madras Road","Old Madras Rd","OMR","OMR East","OMR-East"}', 'area', 'curated', 19),
  ('CV Raman Nagar', 'cv-raman-nagar', '{"CV Raman Nagar","CV Raman","C V Raman Nagar"}', 'area', 'curated', 20),
  ('Brookefield', 'brookefield', '{"Brookefield","Brooke Field"}', 'area', 'curated', 21),
  ('Marathahalli', 'marathahalli', '{"Marathahalli","Marathalli"}', 'area', 'curated', 22),
  ('Electronic City', 'electronic-city', '{"Electronic City","E-City","ECity"}', 'area', 'curated', 23),
  ('Diamond District', 'diamond-district', '{"Diamond District","Diamond District Layout"}', 'area', 'curated', 24),
  ('Jayanagar', 'jayanagar', '{"Jayanagar"}', 'area', 'curated', 25),
  ('Rajajinagar', 'rajajinagar', '{"Rajajinagar","Rajaji Nagar"}', 'area', 'curated', 26),
  ('Banashankari', 'banashankari', '{"Banashankari","BSK","Banskari"}', 'area', 'curated', 27),
  ('Malleswaram', 'malleswaram', '{"Malleswaram","Malleshwaram"}', 'area', 'curated', 28),
  ('Hebbal', 'hebbal', '{"Hebbal"}', 'area', 'curated', 29),
  ('Yelahanka', 'yelahanka', '{"Yelahanka"}', 'area', 'curated', 30),
  ('KR Puram', 'kr-puram', '{"KR Puram","Krishnarajapuram","Kr Puram"}', 'area', 'curated', 31),
  ('Ulsoor', 'ulsoor', '{"Ulsoor","Halasuru"}', 'area', 'curated', 32),
  ('Domlur', 'domlur', '{"Domlur","Dommlur"}', 'area', 'curated', 33),
  ('Hennur', 'hennur', '{"Hennur","Hennur Road"}', 'area', 'curated', 34),
  ('Thanisandra', 'thanisandra', '{"Thanisandra","Thanisandra Main Road"}', 'area', 'curated', 35),
  ('Kalyan Nagar', 'kalyan-nagar', '{"Kalyan Nagar","Kalyannagar"}', 'area', 'curated', 36),
  ('Frazer Town', 'frazer-town', '{"Frazer Town","Fraser Town"}', 'area', 'curated', 37),
  ('Cooke Town', 'cooke-town', '{"Cooke Town","Cook Town"}', 'area', 'curated', 38),
  ('Sadashivanagar', 'sadashivanagar', '{"Sadashivanagar","Sadashiva Nagar"}', 'area', 'curated', 39),
  ('Old Airport Road', 'old-airport-road', '{"Old Airport Road","OAR"}', 'area', 'curated', 40),
  ('Varthur', 'varthur', '{"Varthur","Varthur Road"}', 'area', 'curated', 41),
  ('Panathur', 'panathur', '{"Panathur","Panathur Main Road"}', 'area', 'curated', 42),
  ('Gunjur', 'gunjur', '{"Gunjur","Gunjur Village"}', 'area', 'curated', 43),
  ('Kadugodi', 'kadugodi', '{"Kadugodi","Kadugodi Tree Park"}', 'area', 'curated', 44),
  ('Mahadevapura', 'mahadevapura', '{"Mahadevapura","Mahadevapura Post"}', 'area', 'curated', 45),
  ('Kasavanahalli', 'kasavanahalli', '{"Kasavanahalli","Kasavanahalli Main Road"}', 'area', 'curated', 46),
  ('Bannerghatta Road', 'bannerghatta-road', '{"Bannerghatta Road","Bannerghatta","BG Road"}', 'area', 'curated', 47),
  ('Kanakapura Road', 'kanakapura-road', '{"Kanakapura Road","Kanakapura"}', 'area', 'curated', 48),
  ('Uttarahalli', 'uttarahalli', '{"Uttarahalli","Uttarhalli"}', 'area', 'curated', 49),
  ('Central', 'central', '{"Central","Central Bangalore","Bangalore Central"}', 'area', 'curated', 90)
on conflict (slug) do nothing;
